#!/usr/bin/env bash

if [ "$SUPERVISOR_PHP_USER" != "root" ] && [ "$SUPERVISOR_PHP_USER" != "sail" ]; then
    echo "You should set SUPERVISOR_PHP_USER to either 'sail' or 'root'."
    exit 1
fi

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

until mysqladmin ping -h "$DB_HOST" -u"$DB_USERNAME" -p"$DB_PASSWORD" --silent; do
  echo "Waiting for the MYSQL service to be ready..."
  sleep 2
done

if ! php artisan migrate:status --no-ansi | grep -q '| Y'; then
  echo "⚙️ First-time Laravel setup running..."

  php artisan key:generate --force
  echo "✅ Laravel app key has been generated successfully"

  php artisan migrate:fresh --seed
  echo "✅ Migrations has been run successfully"
fi

if [ ! -d node_modules ]; then
    echo "📦 Download node modules package"
    npm install
    npm run build
    echo "✅ Assets have been successfully loaded"
fi

if [ $# -gt 0 ]; then
    if [ "$SUPERVISOR_PHP_USER" = "root" ]; then
        exec "$@"
    else
        exec gosu $WWWUSER "$@"
    fi
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
